apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loket
resources:
  - namespace.yaml
  - oracle-secret.yaml
  - oracle-pvc.yaml
  - oracle-deployment.yaml
  - oracle-service.yaml
  - app-deployment.yaml
  - app-service.yaml

