apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loket-authn.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "loket-authn.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
stringData:
  SECURITY_JWT_SECRET: "{{ .Values.env.security_jwt_secret }}"

